### ISSUE TITLE
Filter messages before attempting broadcast

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-kafka.java#15]
Messages for a given topic are currently received by internal consumers that then filter according to specific criteria such as message key, message header values and available flow control window before being delivered.

We can optimize the time spent determining such a filter match by promoting the static nature of the matching criteria to be executed once on behalf of a set of consumer with the same criteria, rather than executing the static aspects once per consumer.

The dynamic aspect of the match, specifically available flow control window, must still be evaluated by each consumer.

**Comment by cmebarrow** [comment]
@jfallows Please close since this was implemented using the MessageDispatcher abstraction, PR https://github.com/reaktivity/nukleus-kafka.java/pull/38.

**Comment by jfallows** [comment]
thanks @cmebarrow
