### ISSUE TITLE
Detect and Fetch from all partitions for a given topic

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-kafka.java#2]
The total number of Kafka partitions for a given topic is configured at the broker cluster, whereas `Fetch` requests are made to a specific topic partition.

Therefore, Kafka clients wishing to receive all messages for a given topic including all partitions, must first discover the number of partitions to issue a complete `Fetch` request.

Note: after properly detecting cluster members via #1, the `Fetch` request for each topic partition must also be directed at an appropriate cluster member broker that is either the topic partition leader or a valid replica.

**Comment by cmebarrow** [comment]
@jfallows My reading of the doc is fetch requests have to be directed at the topic partition leader

**Comment by jfallows** [comment]
@cmebarrow it is my understanding that `Produce` requests must be directed at the topic partition leader, but that `Fetch` requests can be directed to any valid replica, which will serve consistent messages at the same message offset.

**Comment by jfallows** [comment]
Fixed by #3
