### ISSUE TITLE
Add test cases for NPE's in getHighestOffset (and getLowestOffset) and OnPartitionResponse

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-kafka.java#26]
We need to add test cases for the fix done in https://github.com/reaktivity/nukleus-kafka.java/pull/25
These should force the condition where floor is null in `NetworkConnectionPool.NetworkTopic.getHighestOffset(int)` and ceiling is null in `org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool.NetworkTopic.getLowestOffset(int)`

Hint: the test cases will probably be similar to test FetchIT.shouldHandleFetchResponseAfterUnsubscribe, but will probably need to involve multiple partitions and possibly a mixture of live and historical consumers to reproduce the condition.

**Comment by cmebarrow** [comment]
#### Test cases 1 and 2

NPE in NetworkTopic.getHighestOffset (on live fetch connection) and getLowestOffset (on historical fetch connection), happening because the search in the partitions navigable map returns null.

One scenario that could cause this would be two subscribers on different fetch keys mapping to different partitions.  One unsubscribes before the fetch response comes in.  The fact that the other has not yet unsubscribed means there is still an entry in  topicsByName. But because the first  unsubscribed there  is no longer any entry matching the partition in the partitions map.

#### Test case 3

NPE in NetworkTopic.handleProgress called from ClientAcceptStream.onPartitionResponse, happening because partitions.floor(candidate) returns  null.

**Comment by jfallows** [comment]
`kafka` nukleus has been refactored, no longer susceptible to this issue.
