### ISSUE TITLE
Stream to historical clients while minimizing impact on the live stream

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-kafka.java#4]
Kafka `FETCH` API requires a single partition offset per topic partition and one `FETCH` at a time, so to add parallelism of historical message retrieval and live message retrieval would likely require parallel connections.

**Comment by cmebarrow** [comment]
Test case:
- client 1 subscribes at offset 0
- a fetch[offset=0] request is done on the Kafka live fetch connection and delivers message[offset=0] to client 1
- client 2 subscribes at offset 0
- a fetch[offset=0] request is done on the Kafka historical fetch connection and delivers message[offset =0] to client 2
- a fetch[offset=1] request is done and delivers message[offset=1] to both clients

**Comment by cmebarrow** [comment]
Note that historical subscribers can only catch up to the live one if they can consume messages faster than live messages are being produced and consumed.

**Comment by jfallows** [comment]
That's correct, any conflation would happen outside this nukleus, such that even slower clients would appear fast to this nukleus if messages are being conflated to catch up / keep up.

**Comment by cmebarrow** [comment]
Fixes available in https://github.com/reaktivity/nukleus-kafka.spec/pull/4 and https://github.com/reaktivity/nukleus-kafka.java/pull/8

**Comment by cmebarrow** [comment]
@jfallows Please close this since the above PR's have now been merged.
