### ISSUE TITLE
Until compression is supported, skip compressed record batches

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-kafka.java#60]
Include output indicating skip has occurred so that logs will explain why compressed messages are not being delivered.

For example, `SNAPPY` compression injects bytes near start of each `record` in a compression `record batch`.

<img width="740" alt="screen shot 2018-03-28 at 1 33 04 pm" src="https://user-images.githubusercontent.com/2099911/38054711-a16f5a5a-328c-11e8-962e-17f9abde54e5.png">

Note: according to [Kafka Protocol Guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets), the `record batch` `attributes` indicate the compression codec used for the `record batch`.

```
The lowest 3 bits contain the compression codec used for the message.
```
`0 = NONE`, `1 = GZIP`, `2 = SNAPPY`

**Comment by jitsni** [comment]
https://github.com/reaktivity/nukleus-kafka.java/pull/121

**Comment by cmebarrow** [comment]
@jitsni Please close if this has now been fixed

**Comment by jitsni** [comment]
It is fixed. @jfallows can you close it
