### ISSUE TITLE
Skip Record Batches with Control bit set

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-kafka.java#61]
Note: according to [Kafka Protocol Guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets)
```
The sixth lowest bit indicates whether the RecordBatch includes a control message. 1 indicates that 
the RecordBatch is contains a control message, 0 indicates that it doesn't. Control messages are used 
to enable transactions in Kafka and are generated by the broker. Clients should not return control 
batches (ie. those with this bit set) to applications.
```

**Comment by cmebarrow** [comment]
Furthermore, according to https://kafka.apache.org/documentation/#messageformat, A control batch contains a **single record** called the control record. So we can safely skip the entire batch in this case.

**Comment by jitsni** [comment]
PR https://github.com/reaktivity/nukleus-kafka.java/pull/121

**Comment by cmebarrow** [comment]
@jitsni Can we close this?

**Comment by jitsni** [comment]
@jfallows can you close this
